# Generated by Django 4.1.2 on 2022-10-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('idAlumno', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidopat', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellidomat', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('dni', models.IntegerField(verbose_name='Dni')),
                ('codigo_ins', models.IntegerField(verbose_name='Codigo Institucional')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
